spring:
  application:
    name: client_test

server:
  port: 8080


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: false
    serviceUrl:
      defaultZone: http://huarh:runghall@localhost:1111/eureka/,http://huarh:runghall@runghall.local:1112/eureka/,http://huarh:runghall@runghall.localhost:1113/eureka/

security:
  user:
    name: huarh
    password: runghall