spring:
  application:
    name: eureka-server

server:
  port: 1111

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://huarh:runghall@runghall.local:1112/eureka/,http://huarh:runghall@runghall.localhost:1113/eureka/
    fetch-registry: false

security:
  user:
    name: huarh
    password: runghall